#ifndef __DataGame__
#define __DataGame__

#define CRAB_PT  10
#define SQUID_PT  20
#define OCTO_PT  40
#define LAZE_PT  60

Type LevelHomepage[20][4] =
{
  {EMPTY, CRAB, EMPTY, EMPTY}, // Level 1
  {EMPTY, CRAB, SQUID, EMPTY}, // Level 2
  {EMPTY, CRAB, SQUID, EMPTY}, // Level 3
  {EMPTY, CRAB, SQUID, EMPTY}, // Level 4
  {CRAB, SQUID, OCTO, EMPTY},  // Level 5
  //--------------------------------------
  {EMPTY, CRAB, OCTO, EMPTY}, // Level 6
  {CRAB, SQUID, OCTO, EMPTY}, // Level 7
  {EMPTY, OCTO, SQUID, EMPTY}, // Level 8
  {EMPTY, CRAB, OCTO, EMPTY}, // Level 9
  {CRAB, SQUID, LAZE, EMPTY}, // Level 10
  //--------------------------------------
  {CRAB, SQUID, LAZE, EMPTY}, // Level 11
  {CRAB, SQUID, OCTO, LAZE}, // Level 12
  {CRAB, OCTO, LAZE, EMPTY}, // Level 13
  {SQUID, OCTO, LAZE, EMPTY}, // Level 14
  {EMPTY, CRAB, LAZE, EMPTY}, // Level 15
  //--------------------------------------
  {CRAB, SQUID, LAZE, EMPTY}, // Level 16
  {EMPTY, SQUID, LAZE, EMPTY}, // Level 17
  {CRAB, OCTO, LAZE, EMPTY}, // Level 18
  {SQUID, OCTO, LAZE, EMPTY}, // Level 19
  {EMPTY, OCTO, LAZE, EMPTY} // Level 20
  //--------------------------------------
};

Type LevelEnemy[80][8] =
{
  //----              LEVEL 1               ----//
  {CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB},
  {CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB},
  {CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB},
  {CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB},
  //----              LEVEL 2                       ----//
  {SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID},
  {CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB},
  {CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB},
  {CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB},
  //----              LEVEL 3                       ----//
  {SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID},
  {SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID},
  {CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB},
  {CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB},
  //----              LEVEL 4                       ----//
  {SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID},
  {SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID},
  {SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID},
  {CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB},
  //----              LEVEL 5                       ----//
  {OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO},
  {SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID},
  {CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB},
  {CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB},
  //----              LEVEL 6                       ----//
  {OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO},
  {OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO},
  {CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB},
  {CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB},
  //----              LEVEL 7                       ----//
  {OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO},
  {OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO},
  {SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID},
  {CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB},
  //----              LEVEL 8                       ----//
  {OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO},
  {OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO},
  {SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID},
  {SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID},
  //----              LEVEL 9                   ----//
  {OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO},
  {OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO},
  {OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO},
  {CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB},
  //----              LEVEL 10                  ----//
  {LAZE, LAZE, LAZE, LAZE, LAZE, LAZE, LAZE, LAZE},
  {SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID},
  {CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB},
  {CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB},
  //----              LEVEL 11                  ----//
  {LAZE, LAZE, LAZE, LAZE, LAZE, LAZE, LAZE, LAZE},
  {SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID},
  {SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID},
  {CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB},
  //----              LEVEL 12                  ----//
  {LAZE, LAZE, LAZE, LAZE, LAZE, LAZE, LAZE, LAZE},
  {OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO},
  {SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID},
  {CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB},
  //----             LEVEL 13                  ----//
  {LAZE, LAZE, LAZE, LAZE, LAZE, LAZE, LAZE, LAZE},
  {OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO},
  {OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO},
  {CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB},
  //----          LEVEL 14                  ----//
  {LAZE, LAZE, LAZE, LAZE, LAZE, LAZE, LAZE, LAZE},
  {OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO},
  {OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO},
  {SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID},
  //----          LEVEL 15                  ----//
  {LAZE, LAZE, LAZE, LAZE, LAZE, LAZE, LAZE, LAZE},
  {LAZE, LAZE, LAZE, LAZE, LAZE, LAZE, LAZE, LAZE},
  {CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB},
  {CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB},
  //----          LEVEL 16                  ----//
  {LAZE, LAZE, LAZE, LAZE, LAZE, LAZE, LAZE, LAZE},
  {LAZE, LAZE, LAZE, LAZE, LAZE, LAZE, LAZE, LAZE},
  {SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID},
  {CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB},
  //----          LEVEL 17                  ----//
  {LAZE, LAZE, LAZE, LAZE, LAZE, LAZE, LAZE, LAZE},
  {LAZE, LAZE, LAZE, LAZE, LAZE, LAZE, LAZE, LAZE},
  {SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID},
  {SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID},
  //----          LEVEL 18                  ----//
  {LAZE, LAZE, LAZE, LAZE, LAZE, LAZE, LAZE, LAZE},
  {LAZE, LAZE, LAZE, LAZE, LAZE, LAZE, LAZE, LAZE},
  {OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO},
  {CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB, CRAB},
  //----          LEVEL 19                  ----//
  {LAZE, LAZE, LAZE, LAZE, LAZE, LAZE, LAZE, LAZE},
  {LAZE, LAZE, LAZE, LAZE, LAZE, LAZE, LAZE, LAZE},
  {OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO},
  {SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID, SQUID},
  //----          LEVEL 20                  ----//
  {LAZE, LAZE, LAZE, LAZE, LAZE, LAZE, LAZE, LAZE},
  {LAZE, LAZE, LAZE, LAZE, LAZE, LAZE, LAZE, LAZE},
  {OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO},
  {OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO, OCTO}
};

int LevelEnemyPoint[80][8] =
{
  //----      LEVEL 1       ----//
  {CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT},
  {CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT},
  {CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT},
  {CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT},
  //----      LEVEL 2       ----//
  {SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT},
  {CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT},
  {CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT},
  {CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT},
  //----      LEVEL 3       ----//
  {SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT},
  {SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT},
  {CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT},
  {CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT},
  //----      LEVEL 4       ----//
  {SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT},
  {SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT},
  {SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT},
  {CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT},
  //----                           LEVEL 5                                   ----//
  {OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT},
  {SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT},
  {SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT},
  {SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT},
  //----                           LEVEL 6                                   ----//
  {OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT},
  {OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT},
  {CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT},
  {CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT},
  //----                           LEVEL 7                                   ----//
  {OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT},
  {OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT},
  {SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT},
  {CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT},
  //----                           LEVEL 8                                   ----//
  {OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT},
  {OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT},
  {SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT},
  {SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT},
  //----                        LEVEL 9                             ----//
  {OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT},
  {OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT},
  {OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT},
  {CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT},
  //----                        LEVEL 10                                    ----//
  {LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT},
  {SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT},
  {CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT},
  {CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT},
  //----                        LEVEL 11                                    ----//
  {LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT},
  {SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT},
  {SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT},
  {CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT},
  //----                        LEVEL 12                                 ----//
  {LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT},
  {OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT},
  {SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT},
  {CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT},
  //----                        LEVEL 13                                 ----//
  {LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT},
  {OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT},
  {OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT},
  {CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT},
  //----                        LEVEL 14                                 --//
  {LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT},
  {OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT},
  {OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT},
  {SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT},
  //----                        LEVEL 15                                 --//
  {LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT},
  {LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT},
  {CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT},
  {CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT},
  //----                        LEVEL 16                                --//
  {LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT},
  {LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT},
  {SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT},
  {CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT},
  //----                        LEVEL 17                                -//
  {LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT},
  {LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT},
  {SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT},
  {SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT},
  //----                        LEVEL 18                                -//
  {LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT},
  {LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT},
  {OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT},
  {CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT, CRAB_PT},
  //----                        LEVEL 19                                -//
  {LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT},
  {LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT},
  {OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT},
  {SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT, SQUID_PT},
  //----                        LEVEL 20                                -//
  {LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT},
  {LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT, LAZE_PT},
  {OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT},
  {OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT, OCTO_PT}  
};
#endif
